name       : mongodb
version    : 3.4.0
release    : 1
source     :
    - https://fastdl.mongodb.org/src/mongodb-src-r3.4.0.tar.gz : 5a904b66d09e4d15f3ed35028a004640afcba5d8ecb5644165bd08cd7eb79df6
license    : AGPL-3.0
component  : database
summary    : A high-performance, open source, schema-free document-oriented database
description: |
    MongoDB is a high-performance, open source, schema-free document-oriented database
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libsasl2)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - scons
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/fix-for-boost-1.62.0.patch
build      : |
    scons install \
        --prefix=$installdir/usr \
        --use-system-boost \
        --use-system-pcre \
        --use-system-snappy \
        --use-system-yaml \
        --use-system-zlib \
        --use-sasl-client \
        --ssl \
        --disable-warnings-as-errors \
        --jobs $(nproc)
install    : |-
    install -Dm644 $pkgfiles/mongodb.service $installdir%libdir%/systemd/system/mongodb.service
    install -Dm644 $pkgfiles/mongodb.sysusers $installdir%libdir%/sysusers.d/mongodb.conf
    install -Dm644 $pkgfiles/mongodb.conf $installdir/usr/share/defaults/mongodb/mongodb.conf
