name       : mongodb
version    : 3.4.10
release    : 5
source     :
    - https://fastdl.mongodb.org/src/mongodb-src-r3.4.10.tar.gz : 443800ca4f52fa613b29052f5f76abc0ccc477451b55f3665b61819f28ace2f3
license    : AGPL-3.0
component  : database
summary    : A high-performance, open source, schema-free document-oriented database
description: |
    MongoDB is a high-performance, open source, schema-free document-oriented database
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libsasl2)
    - pkgconfig(wiredtiger)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - libpcap-devel
    - scons
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/fix-for-boost-1.62.0.patch
build      : |
    scons install \
        --prefix=$installdir/usr \
        --use-system-boost \
        --use-system-pcre \
        --use-system-snappy \
        --use-system-wiredtiger \
        --use-system-yaml \
        --use-system-zlib \
        --use-sasl-client \
        --ssl \
        --disable-warnings-as-errors \
        --jobs $(nproc)
install    : |
    install -Dm 00644 $pkgfiles/mongodb.service $installdir/%libdir%/systemd/system/mongodb.service
    install -Dm 00644 $pkgfiles/mongodb.sysusers $installdir/%libdir%/sysusers.d/mongodb.conf
    install -Dm 00644 $pkgfiles/mongodb.tmpfiles $installdir/%libdir%/tmpfiles.d/mongodb.conf
    install -Dm 00644 $pkgfiles/mongodb.conf $installdir/usr/share/defaults/mongodb/mongodb.conf
    install -Dm 00755 $pkgfiles/mongodb.sh $installdir/usr/share/mongodb/mongodb.sh
