name       : mongodb
version    : 3.6.3
release    : 7
source     :
    - https://fastdl.mongodb.org/src/mongodb-src-r3.6.2.tar.gz : 018788bd31d6953e55cda0ad0771d23e6b78e024a8a6404a80a900c67215b0a7
license    : AGPL-3.0
component  : database
summary    : A high-performance, open source, schema-free document-oriented database
description: |
    MongoDB is a high-performance, open source, schema-free document-oriented database
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libsasl2)
    - pkgconfig(wiredtiger)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - libpcap-devel
    - python-cheetah
    - python-requests
    - python-setuptools
    - python-typing
    - scons
    - snappy-devel
build      : |
    scons install \
        --prefix=$installdir/usr \
        --use-system-boost \
        --use-system-pcre \
        --use-system-snappy \
        --use-system-wiredtiger \
        --use-system-yaml \
        --use-system-zlib \
        --use-sasl-client \
        --ssl \
        --disable-warnings-as-errors \
        %JOBS%
install    : |
    install -Dm 00644 $pkgfiles/mongodb.service $installdir/%libdir%/systemd/system/mongodb.service
    install -Dm 00644 $pkgfiles/mongodb.sysusers $installdir/%libdir%/sysusers.d/mongodb.conf
    install -Dm 00644 $pkgfiles/mongodb.tmpfiles $installdir/%libdir%/tmpfiles.d/mongodb.conf
    install -Dm 00644 $pkgfiles/mongodb.conf $installdir/usr/share/defaults/mongodb/mongodb.conf
    install -Dm 00755 $pkgfiles/mongodb.sh $installdir/usr/share/mongodb/mongodb.sh
