name       : mongodb
version    : 4.2.11
release    : 17
source     :
    - https://fastdl.mongodb.org/src/mongodb-src-r4.2.11.tar.gz : ab5a8b6e967614a8ad67c0ca87124c4f380d4a476508973a7995d54ed902b02e
license    : SSPL-1.0
component  : database
summary    : A high-performance, open source, schema-free document-oriented database
description: |
    MongoDB is a high-performance, open source, schema-free document-oriented database
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libpcap)
    - pkgconfig(libpcre)
    - pkgconfig(libsasl2)
    - pkgconfig(libzstd)
    - pkgconfig(wiredtiger)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - python-cheetah
    - python-psutil
    - python-requests
    - python-typing
    - scons
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/0000-link-against-system-wiredtiger.patch
build      : |
    # --use-system-fmt  The inclusion of these two in the build results in error because mongodb uses
    # --use-system-icu  specific versions of the APIs.

    python3 /usr/bin/scons install \
        --disable-warnings-as-errors \
        --prefix=$installdir/usr \
        --release \
        --use-sasl-client \
        --use-system-boost \
        --use-system-pcre \
        --use-system-snappy \
        --use-system-wiredtiger \
        --use-system-yaml \
        --use-system-zlib \
        --use-system-zstd \
        %JOBS%
install    : |
    install -dm00755 $installdir/usr/share/man/{man1,man5}
    install -Dm00644 $pkgfiles/mongodb.service $installdir/%libdir%/systemd/system/mongodb.service
    install -Dm00644 $pkgfiles/mongodb.sysusers $installdir/%libdir%/sysusers.d/mongodb.conf
    install -Dm00644 $pkgfiles/mongodb.tmpfiles $installdir/%libdir%/tmpfiles.d/mongodb.conf
    install -Dm00644 $pkgfiles/mongodb.conf $installdir/usr/share/defaults/mongodb/mongodb.conf
    install -Dm00755 $pkgfiles/mongodb.sh $installdir/usr/share/mongodb/mongodb.sh
    install -Dm00644 debian/{mongo.1,mongod.1,mongos.1} $installdir/usr/share/man/man1
    install -Dm00644 debian/mongodb-parameters.5 $installdir/usr/share/man/man5
    rm $installdir/usr/bin/install_compass
