name       : mongodb
version    : 4.0.5
release    : 11
source     :
    - https://fastdl.mongodb.org/src/mongodb-src-r4.0.5.tar.gz : d967098fc91d105cdb0f400c8b837e5c2795c3638d7720392bc47afb1efe1c10
license    : SSPL #no SPDX identifier: https://www.mongodb.com/licensing/server-side-public-license
component  : database
summary    : A high-performance, open source, schema-free document-oriented database
description: |
    MongoDB is a high-performance, open source, schema-free document-oriented database
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libpcre)
    - pkgconfig(libsasl2)
    - pkgconfig(wiredtiger)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - libpcap-devel
    - python-cheetah
    - python-requests
    - python-setuptools
    - python-typing
    - scons
    - snappy-devel
build      : |
    scons install \
        --prefix=$installdir/usr \
        --use-system-boost \
        --use-system-pcre \
        --use-system-snappy \
        --use-system-wiredtiger \
        --use-system-yaml \
        --use-system-zlib \
        --use-sasl-client \
        --ssl \
        --disable-warnings-as-errors \
        %JOBS%
install    : |
    install -Dm 00644 $pkgfiles/mongodb.service $installdir/%libdir%/systemd/system/mongodb.service
    install -Dm 00644 $pkgfiles/mongodb.sysusers $installdir/%libdir%/sysusers.d/mongodb.conf
    install -Dm 00644 $pkgfiles/mongodb.tmpfiles $installdir/%libdir%/tmpfiles.d/mongodb.conf
    install -Dm 00644 $pkgfiles/mongodb.conf $installdir/usr/share/defaults/mongodb/mongodb.conf
    install -Dm 00755 $pkgfiles/mongodb.sh $installdir/usr/share/mongodb/mongodb.sh
