name       : mongodb
version    : 5.0.0
release    : 19
source     :
    - https://fastdl.mongodb.org/src/mongodb-src-r5.0.0.tar.gz : 4e0ed3f7f8619541429db8e4740e8b09b49341f92c0ec9210b23dac6935c8f4b
license    : SSPL-1.0
component  : database
summary    : A high-performance, open source, schema-free document-oriented database
description: |
    MongoDB is a high-performance, open source, schema-free document-oriented database
builddeps  :
    - pkgconfig(absl_meta)
    - pkgconfig(libcurl)
    - pkgconfig(libmongoc-1.0)
    - pkgconfig(libpcap)
    - pkgconfig(libpcre)
    - pkgconfig(libsasl2)
    - pkgconfig(libtcmalloc)
    - pkgconfig(libzstd)
    - pkgconfig(wiredtiger)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - libstemmer-devel
    - python-cheetah
    - python-psutil
    - python-regex
    - python-requests
    - pyyaml
    - scons
    - snappy-devel
environment: |
    export CFLAGS="${CFLAGS/-g3/-g1}"
    export CXXFLAGS="${CXXFLAGS/-g3/-g1}"
setup      : |
    %apply_patches
build      : |
    # --use-system-fmt  The inclusion of these two in the build results in error because mongodb uses
    # --use-system-icu  specific versions of the APIs.

    python3 /usr/bin/scons install-core \
        DESTDIR=$installdir \
        PREFIX=/usr \
        --disable-warnings-as-errors \
        --release \
        --use-sasl-client \
        --use-system-abseil-cpp \
        --use-system-boost \
        --use-system-mongo-c \
        --use-system-pcre \
        --use-system-snappy \
        --use-system-stemmer \
        --use-system-tcmalloc \
        --use-system-wiredtiger \
        --use-system-yaml \
        --use-system-zlib \
        --use-system-zstd \
        -j12
install    : |
    install -dm00755 $installdir/usr/share/man/{man1,man5}
    install -Dm00644 $pkgfiles/mongodb.service $installdir/%libdir%/systemd/system/mongodb.service
    install -Dm00644 $pkgfiles/mongodb.sysusers $installdir/%libdir%/sysusers.d/mongodb.conf
    install -Dm00644 $pkgfiles/mongodb.tmpfiles $installdir/%libdir%/tmpfiles.d/mongodb.conf
    install -Dm00644 $pkgfiles/mongodb.conf $installdir/usr/share/defaults/mongodb/mongodb.conf
    install -Dm00755 $pkgfiles/mongodb.sh $installdir/usr/share/mongodb/mongodb.sh
    install -Dm00644 debian/{mongo.1,mongod.1,mongos.1} $installdir/usr/share/man/man1
    install -Dm00644 debian/mongodb-parameters.5 $installdir/usr/share/man/man5
    rm -f $installdir/usr/bin/install_compass
    rm -f $installdir/usr/{LICENSE-Community.txt,MPL-2,README,THIRD-PARTY-NOTICES}
